### PR TITLE
fixes and improvements for embedding

### LINKED ISSUE #466: [BUG] 'Error: Invalid table name' after embedding due to workspace name containing invalid characters
**Describe the bug**
After opening a workspace name with e.g. spaces and braces and running an embed this error is thrown:
`Error populating database Error: Invalid table name ("location_history (Workspace)-documents"): Table names can only contain alphanumeric characters, underscores, hyphens, and periods`

I already wrote a fix for this but it is bundled together with a few more changes. Here is the commit: 88af8c06da84b2a6e989b4c4ef20d13fba448fee

I will create a pull request soon so we can discuss the changes I made.

**To Reproduce**
Open a folder with invalid characters or open a workspace. VSCode adds the _(invalid)_ ` (Workspace)` tag automatically to workspace names.

**Expected behavior**
The embed finishes without issues. 

**API Provider**
Ollama

**Model Name**
all-minilm:latest

**Desktop:**
- OS: MacOS 15.3.2
- VSCode Version: 1.99.2

### PR DESCRIPTION
**Pull request by ton-An**
I added a few improvements and fixes for the embedding feature:
- Fix #466 88af8c06da84b2a6e989b4c4ef20d13fba448fee
- Improve the progress dialog
    - Improve accuracy of progress percentage bae510dcd7c837662e2e3e84795a26d1f4b3d443 4cceeefd6cb97f7604ab577284abd7bb4b6e57b2 6f03bb725e77b38a91dd17dcc97b1a56a0f197af
    - Add currently processing files
    - Switch loading bar from spinner to real progress (indeterminate progress to determinate progress) 
    - Show total time taken at end of embedd
- Fix embedding cancel button not working 4cceeefd6cb97f7604ab577284abd7bb4b6e57b2
- Move processing queue (p-queue) management to an earlier method in the embedding process 4cceeefd6cb97f7604ab577284abd7bb4b6e57b2 283abf355f7597758f1c3ca201ddc1b739c38a74
- Increase concurrency for processing queue
---

A note on the currently processing files display in the dialog:
SCR-20250501-myva
I added it because I find it useful to see the files that are processing for a long time so I know what files I might want to exclude. I would understand, though, if someone doesn't like it. Especially as the height of the dialog tends to jump fairly often. I can't fix that due to limitations of VSCode. 

You would have to take a look and see if you like the display.

### CODE REVIEW

**Comment by ton-An** [comment]
There are two more fixes that are missing from this pull request. 

The bugs are:
- VSCode crashes when embedding large codebases
    - My theory is that it is some sort of memory overflow. Meaning these two arrays grow too large:
https://github.com/twinnydotdev/twinny/blob/330257e2995ecbb50d09c347881125510e4a904b/src/extension/embeddings.ts#L28-L29
- In workspaces with multiple added folders the embedding db gets overwritten after each folder is embedded (as far as I understand it)

I need some clarification before I can write the fixes: 
The data from the previous embed doesn't get used during the new one and the database gets completely dropped before the new data is save, right?

**Comment by ton-An** [comment]
One more addition. @rjmacarthy Can you share your formatter config? :) I keep reformatting files.

**Comment by rjmacarthy** [comment]
Hey thanks for this it lgtm, for the linting the [.eslintrc.cjs](https://github.com/twinnydotdev/twinny/blob/main/.eslintrc.cjs) should be enough?  You can run `npm run lint:fix` to fix the issues also.

**Comment by ton-An** [comment]
> Hey thanks for this it lgtm, for the linting the [.eslintrc.cjs](https://github.com/twinnydotdev/twinny/blob/main/.eslintrc.cjs) should be enough? You can run `npm run lint:fix` to fix the issues also.

Ah, ok. I was using prettier. Makes sense now.

**Comment by ton-An** [comment]
Before getting this merged, can you clarify this? I need it to fix two more bugs. :)

> There are two more fixes that are missing from this pull request.
> 
> The bugs are:
> 
>     * VSCode crashes when embedding large codebases
>       
>       * My theory is that it is some sort of memory overflow. Meaning these two arrays grow too large:
>         https://github.com/twinnydotdev/twinny/blob/330257e2995ecbb50d09c347881125510e4a904b/src/extension/embeddings.ts#L28-L29
> 
>     * In workspaces with multiple added folders the embedding db gets overwritten after each folder is embedded (as far as I understand it)
> 
> 
> I need some clarification before I can write the fixes: The data from the previous embed doesn't get used during the new one and the database gets completely dropped before the new data is saved, right?

**Comment by rjmacarthy** [comment]
> Before getting this merged, can you clarify this? I need it to fix two more bugs. :)
> 
> > There are two more fixes that are missing from this pull request.
> > The bugs are:
> > ```
> > * VSCode crashes when embedding large codebases
> >   
> >   * My theory is that it is some sort of memory overflow. Meaning these two arrays grow too large:
> >     https://github.com/twinnydotdev/twinny/blob/330257e2995ecbb50d09c347881125510e4a904b/src/extension/embeddings.ts#L28-L29
> > 
> > * In workspaces with multiple added folders the embedding db gets overwritten after each folder is embedded (as far as I understand it)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I need some clarification before I can write the fixes: The data from the previous embed doesn't get used during the new one and the database gets completely dropped before the new data is saved, right?

Hey, I'm not sure about the first one, you could be right, I have not spent enough time to investigate it.

For the second one, also you could be right, I remember when I was implementing this I was doing so for speed over accuracy and probably messed some things up, I welcome any changes which improve or fix an unintentional problems.

Many thanks for your help!

Regards

**Comment by ton-An** [comment]
I added the fix for the overflow and the lancedb being overwritten if there are multiple folders in a workspace.

@rjmacarthy Can you run an embedd and check if the data in the lancedb looks good? :)

File: src/extension/embeddings.ts [hunk 1]
```diff
@@ -133,88 +134,164 @@ export class EmbeddingDatabase extends Base {
...
+        const startTime = Date.now()
+
+        const promises = filePaths.map(async (filePath) =>
+          embeddingQueue.add(async () => {
+            if (token.isCancellationRequested) {
+              embeddingQueue.clear()
+              return
+            }
+
+            const fileName = filePath.split("/").pop() || ""
```
Comment (rjmacarthy) [inline src/extension/embeddings.ts:165]: We could use `path.basename`.

**Review by rjmacarthy — APPROVED** [review]
lgtm, many thanks!
